### ISSUE TITLE
Running HiPhase with tumor-normal pair

### ISSUE THREAD

**Issue by aysegokce** [PacificBiosciences/HiPhase#26]
Hello,
Thank you for developing HiPhase! I liked how HiPhase handles haplotagging supplementary alignments. Is[ this](https://github.com/PacificBiosciences/HiPhase/issues/5#issuecomment-1536659101) by default, or should I pass a parameter?

Is there a suggested workflow for tumor-normal pairs? We usually run the Clair3 (or DV) + whatshap phase with normal and then use whatshap to haplotag both tumor and normal using the phased vcf. Is there such functionality? 

Thank you,
Ayse

**Comment by holtjma** [comment]
Hi @aysegokce,

> Thank you for developing HiPhase! I liked how HiPhase handles haplotagging supplementary alignments. Ishttps://github.com/PacificBiosciences/HiPhase/issues/5#issuecomment-1536659101 by default, or should I pass a parameter?

Yes, this is enabled by default.  If you want to *disable* it, you can use the `--no-supplemental-joins` option.

>Is there a suggested workflow for tumor-normal pairs?

In this context, we only officially support "normal" sample types.  Tumor will obviously have a variety of deviations from normal that HiPhase currently does not account for.

>We usually run the Clair3 (or DV) + whatshap phase with normal and then use whatshap to haplotag both tumor and normal using the phased vcf. Is there such functionality?

Just to verify, here is the pipeline I think you're describing; please correct any errors:

1. Run a variant caller on the normal dataset.
2. Phase and haplotag the normal dataset using WhatsHap.
3. Use WhatsHap to haplotag the tumor dataset using the phased VCF from the normal dataset.

Assuming the above is correct, HiPhase currently cannot do step 3. This is because the phasing and tagging steps make the assumption that the dataset and parameters are identical. I believe you would be able to perform steps 1 and 2 with HiPhase, and then the final step with WhatsHap. I suspect that _most_ haplotagging would be correct, but there would likely be some corner cases that don't work well. 

The use case is interesting, but we built HiPhase under the assumption of a single dataset to phase/haplotag. I'll have to think more about how feasible this is with HiPhase.

Matt

**Comment by aysegokce** [comment]
@holtjma Thank you for the explanation. 
Currently, whatshap does not support supplementary alignment phasing. So, it would be nice to have HiPhase work with tumor/normal pairs as well. 
Ayse
