### ISSUE TITLE
[Suggestion] reducing messages to STDOUT to speed up the utility

### ISSUE THREAD

**Issue by davidyuyuan** [PacificBiosciences/HiPhase#32]
HiPhase works great. I'd like to suggest to move the warning messages such as the one below to debug. This would reduce a large amount of messages to STDOUT. The log can be less cluttered and the execution can be faster without major changes.

[2024-04-15T18:17:31.161Z WARN  hiphase::writers::ordered_vcf_writer] Received 'error seeking to "chrUn_KI270512v1":0 in indexed file', while seeking to chrUn_KI270512v1:0-18446744073709551615 in vcf #0, likely no variants present

**Comment by holtjma** [comment]
Hello,

While this would reduce log clutter, it may also mask out legitimate errors in the underlying htslib crate/library that HiPhase is using. Currently, the errors from `rust_htslib` are passed through as warnings in this context, allowing users like yourself to identify issues with the input files that would be otherwise hidden without the warning.  We could potentially add an option disable the messages, but we would still leave these warnings on by default.

I wouldn't worry about run-time of the output, it is _extremely_ insignificant relative to the rest of the phasing process.

Matt

**Comment by davidyuyuan** [comment]
Thanks, Matt. An option to turn it off would be great.

**Comment by holtjma** [comment]
In the hundred of samples we've run internally, we haven't found anything significant that those messages were capturing that were not caught elsewhere in the code.  As a result, we elected to just downgrade them to DEBUG level. 

This should be resolved in v1.4.1, thanks for the suggestion!
